---
title: "Journalism: A Dangerous Profession"
author: "Daniel Marcelino"
date: "September 22, 2016"
output: html_document
---

https://cpj.org/killed/cpj-database.xls

Talking to a friend these days about dangerous profession, he came up with the argument that journalism is such a dangerous profession; he's journalis by the way. I was'nt quite conviced about his claim, but he gave me some clues, so I decided to conduct some research on this. I never realized that journalism is a very dangerous profession indeed. 

There is a committee to protect journalists, which also provides some bits of information. From this source, 

For additional information, including the list of the journalists killed in 2012, visit:

Journalism is a very dangerous profession. Many journalists are killed every year around the world while covering everything from business and sports to revolutions, wars, political upheavals, corruption, human rights violations and more.

In 2012 alone, 103 journalists were killed around the globe. Motives were confirmed for 70 of them. The deadliest countries for journalists in 2012 were Syria (28 deaths), Somalia (12 deaths), Pakistan (7 deaths), and Brazil (4 deaths). The motives where the confirmed in these cases.

The way journalists are killed, range from crossfire or combat to murder. Impunity is a shocking 100% for murder cases. More detail in the chart below:


CPJ began compiling detailed records on journalist deaths in 1992. We apply strict journalistic standards when investigating a death. One important aspect of our research is determining whether a death was work-related. As a result, we classify deaths as "motive confirmed" or "motive unconfirmed."

We consider a case "confirmed" only if we are reasonably certain that a journalist was murdered in direct reprisal for his or her work; was killed in crossfire during combat situations; or was killed while carrying out a dangerous assignment such as coverage of a street protest. We do not include journalists who are killed in accidents such as car or plane crashes.

We include only confirmed cases in the statistical analyses in this database.

When the motive is unclear, but it is possible that a journalist was killed because of his or her work, CPJ classifies the case as "unconfirmed" and continues to investigate. We regularly reclassify cases based on our ongoing research.

Our archives include narrative capsules of all journalists killed, including the cases in which the motive is unconfirmed. In cases where the place of death is incidental to the journalist's killing, we have listed the country where the fatal attack occurred to be the place of the journalist's death (for example, in a case where a journalist is hit by shrapnel in one country and evacuated to another, where he or she dies, CPJ lists the country in which he or she was hit as the place of death).

CPJ defines journalists as people who cover news or comment on public affairs through any media -- including in print, in photographs, on radio, on television, and online. We take up cases involving staff journalists, freelancers, stringers, bloggers, and citizen journalists. The combination of daily reporting and statistical data forms the basis of our case-driven and long-term advocacy.

In 2003, CPJ began documenting the deaths of media support workers. We did so in recognition of the vital role these individuals play in newsgathering. These workers include translators, drivers, fixers, and administrative workers.

Our archives include narrative capsules for media workers killed on duty. These cases are not included our statistical analyses.
