# Doctor Who (2005), Series Six Plus Christmas Special

Premise

“No, look, there’s a blue box. It’s bigger on the inside than it is on the outside. It can go anywhere in time and space and sometimes even where it’s meant to go. And when it turns up, there’s a bloke in it called The Doctor and there will be stuff wrong and he will do his best to sort it out and he will probably succeed ’cause he’s awesome. Now sit down, shut up, and watch ‘Blink’.” — Neil Gaiman

Series Six Plot

The series this year revolved around two central points which were (1) the death of The Doctor and (2) the revelation of who River Song really is. Or was. Or will be. Tenses are difficult when it comes to DW! And then when that was all resolved, we had a Christmas Special inspired by the C. S. Lewis novel The Lion, The Witch and The Wardrobe.


Verdict

First off, the opening two episodes were brilliant with the opening set of scenes introducing us to The Doctor’s death in the future. Just absolutely bloody brilliant. We are introduced to the Silence which are a group of aliens who you can only remember whilst looking at them because once you turn away you completely forget that there were ever there. This is semi-creepy in its own right but get’s bumped up to a who new level when Amy has to mark her own skin each time she encounters a Silent to remind herself that she’s seen one and needs to get the hell out of where ever she is – but because she forgets she ends up being covered in more and more marks which tells her that she is in serious trouble. Very creepy indeed and therefore very awesome. What makes the Silence an even more deadly foe is that when they say something it is taken as a subliminal message to the person hearing it and then they act on it but have no idea why they’ve done what they’ve just done. This latter point is ultimately the Silence’s undoing because The Doctor tricks one Silent into saying “you should kill us onsite”, records it, and then plants into the one piece of footage every human in the future is likely to see at some point in their lifetimes – the video footage of the moon landing. Nobody will remember seeing the Silent but they will act on that one message and not even realise why they’re doing it. Bloody writing genius that is and that’s just one of the reasons why Steven Moffat is my favourite script writer.

Other notable, none series story arc, episodes are Neil Gaiman’s “The Doctor’s Wife” in which we meet Idris, a physical manifestation of The Doctor’s time travelling spaceship (the TARDIS) and Tom MacRae’s “The Girl Who Waited” in which we see an aged version of Amy who has been living in seclusion for many years. Both are excellent episodes with tons of  re-watch factor.

Back to the series story arc, we get a revelation of who River is in the fabulous episode “A Good Man Goes To War” which is one of the fastest paced episodes I can remember and which delivers on almost all fronts. Special mention to Rory who proves in episode, and yet again in the series, why is may just be the most bad-ass companion of them all, love me a bit of Rory I do! This episode is then followed by one of the best titles of any Doctor Who episode “Let’s Kill Hittler” in which we get more River revelations.

Then we have the final in which The Doctor escapes death, which while a lot of fun, seemed like a big cheat given the build up to that moment. I know it makes sense and have no real problem with that, it’s just that when you start the series with The Doctor’s death, you can’t help but hope that there’s going to be a bigger pay-off in how that is dealt with. But still, a fun episode.

Overall it was a most excellent series and I feel Doctor Who has never been better since it’s return in 2005.

Oh, and the Christmas Special. I wasn’t too impressed by it (I much preferred last years which took inspiration for Dickens “A Christmas Carol” and which I still maintain is among the best ever Doctor Who episodes), but it had some great jokes and was entertaining at least. I just didn’t feel for any of the characters that much and I really need that connection in order to enjoy a story. However, the final scene in which The Doctor visits Amy & Rory unannounced for Christmas Dinner and then is told that they already have a place set up for him and in fact always have a place set aside for him… well, I’ll admit that I had a couple of tears running down my cheeks because of his private reaction to knowing that he has a place there and that he can still feel such emotions.

Bring on series seven!

  Edit

BTW, my previous post has a chart of British TV ratings for the last 50 odd years of first run Doctor Who episodes.

Plotting Doctor Who Ratings (1963-2011) With R



Introduction

First day back to work after New Year celebrations and my brain doesn’t really want to think too much. So I went out for lunch and had a nice walk in the park. Still had 15 minutes to kill before my lunch break was over and so decided to kill some time with a quick web scraping exercise in R.

Objective

Download the last 49 years of British TV ratings data for the programme Doctor Who (the longest-running science fiction television show in the world and which is also the most successful science fiction series of all time, in terms of its overall broadcast ratings, DVD and book sales and iTunes traffic) and make a simple plot of it.

Method

Ratings are available from doctorwhonews.net as a series of page separated tables. This means that we can use the RCurl and XML packages to download the first seed webpage, extract the table of ratings, and use XPath to get the weblink to the next page of ratings. Due to time constraints I’m not going to optimise any of this (though given the small data set it probably doesn’t need optimisation anyway).


get_doctor_who_ratings <- function() {
  # load packages
  require(RCurl)
  require(XML)

  # return Title, Date and Rating
  format_df <- function(df) {
    data.frame(Date = as.POSIXlt(df$Date, format = "%a %d %b %Y"),
               Title = df$Title,
               Rating = as.numeric(gsub("(\\s+).*", "\\1", df$Rating)),
               stringsAsFactors = FALSE)
  }

  # scrape data from web
  get_ratings <- function(u) {
    df.list <- list()
    i <- 1
    while(!is.null(u)) {
      html <- getURL(u)
      doc <- htmlParse(u)
      df.list[[i]] <- readHTMLTable(doc, header = TRUE, which = 1, stringsAsFactors = FALSE)
      u.next <- as.vector(xpathSApply(doc, "//div[@class='nav']/a[text()='NEXT']/@href"))
      if(is.null(u.next)) {
        return(df.list)
      }
      u <- sub("info.*", u.next, u)
      i <- i + 1
    }
    return(df.list)
  }

  ### main function code ###
  # Step 1: get tables of ratings for each page that is avaiable
  u <- "http://guide.doctorwhonews.net/info.php?detail=ratings"
  df.list <- get_ratings(u)

  # Step 2: format ratings into a single data.frame
  df <- do.call("rbind", df.list)
  df <- format_df(df)

  # Step 3: return data.frame
  return(df)
}

# get ratings database
ratings.df <- get_doctor_who_ratings()
head(ratings.df)

Plot

We can plot this data very easily using the Hadley Wickman’s ggplot2 package:

  1
2
3
# do a raw plot
require(ggplot2)
ggplot(ratings.df, aes(x=Date, y=Rating)) + geom_point() + xlab("Date") + ylab("Ratings (millions)") + opts(title = "Doctor Who Ratings (1963-Present) without Context")

