repeats = function(string){
  out = c()
  check.till = floor(nchar(string)/2)
  for (start in 1:nchar(string)){
    for (end in 1:check.till){
      pat = substr(string,start,start+end)
      repeats = length(gregexpr(pat,string)[[1]])
      length = nchar(pat)
      if (length >= 2) out = rbind(out, c(pat, repeats, length))
    }
  }
  out = as.data.frame(out, stringsAsFactors = F)
  colnames(out) = c("Pattern","Repeats","Pat.Length")
  out$Repeats = as.integer(out$Repeats)
  out$Pat.Length = as.integer(out$Pat.Length)
  out = out[out$Repeats > 1,]
  out = out[order(out[,2],out[,3],decreasing = T),]
  out = out[1,]
  out[is.na(out)] = 0
  return(out)
}



I'm not completely sure if this is a solution, but what I tried is to split the vector in all unique combinations.

My idea was that all combinations are included in the upper half of a "diagonal-matrix":

d <- c("3412123401234")
# create function
make.matrix <- function(x,y) {
vl <- nchar(d)
OUT <- seq(x,nchar(y),1)
if(length(OUT) < vl) OUT <- c(OUT,rep(NA,vl-length(OUT)))
OUT
}
mm <- sapply(1:nchar(d), make.matrix, d)
mm

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
tmp    1    2    3    4    5    6    7    8    9    10    11    12    13
tmp    2    3    4    5    6    7    8    9   10    11    12    13    NA
tmp    3    4    5    6    7    8    9   10   11    12    13    NA    NA
tmp    4    5    6    7    8    9   10   11   12    13    NA    NA    NA
tmp    5    6    7    8    9   10   11   12   13    NA    NA    NA    NA
tmp    6    7    8    9   10   11   12   13   NA    NA    NA    NA    NA
tmp    7    8    9   10   11   12   13   NA   NA    NA    NA    NA    NA
tmp    8    9   10   11   12   13   NA   NA   NA    NA    NA    NA    NA
tmp    9   10   11   12   13   NA   NA   NA   NA    NA    NA    NA    NA
tmp   10   11   12   13   NA   NA   NA   NA   NA    NA    NA    NA    NA
tmp   11   12   13   NA   NA   NA   NA   NA   NA    NA    NA    NA    NA
tmp   12   13   NA   NA   NA   NA   NA   NA   NA    NA    NA    NA    NA
tmp   13   NA   NA   NA   NA   NA   NA   NA   NA    NA    NA    NA    NA
Now I split the vector with the str_sub function of the stringr package based on the start values of the first row with each other row of the matrix mm

library(stringr)
mm2 <- sapply(2:nrow(mm), function(x,y) str_sub(string= y, start= mm[1,], end= mm[x,]), d)
Finally the count of the unique patterns:

counts <- sort(table(mm2),decreasing = T)
Your desired output:

res <- data.frame("nlength"=sapply(names(counts),nchar),"counts"=counts)
head(res)
nlength counts
